### ISSUE TITLE
I cant get the scrip to up the bitrate to work

### ISSUE THREAD

**Issue by johannesschander** [alexandre-leites/belabox-utilities#1]
File belaUI.js is read-only; trying to patch anyway
patch: **** Can't create temporary file ./belaUI.js.olLl8Zs : Permission denied

Any clue why? Thank you kindly!

**Comment by alexandre-leites** [comment]
Hello!

Have you tried the [How to Root](https://github.com/alexandre-leites/belabox-utilities/blob/main/docs/root.md) first? All patches needs to be executed as the root user in order to work.

I'm not with mine currently, but it would still be working fine.

**Comment by edinsof** [comment]
worked for me on Orange Pi 5 Plus. root is required
